---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: repo-github
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/grupo10-CC3S2/Proyecto7-PC4
