---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustomization-github
  namespace: flux-system
spec:
  interval: 30s
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: repo-github
