apiVersion: v1
kind: Service
metadata:
  name: timeserver
  namespace: default
spec:
  selector:
    pod: timeserver-pod
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer