name: CI
on: [push, pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v4

    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install -r requirements.txt

    - name: Start minikube
      uses: medyagh/setup-minikube@latest

    - name: Build docker images
      run: |
        docker build -t timeserver:v3 app
    
    - name: Try the cluster!
      run: kubectl get pods -A

    - name: Build image
      run: |
        minikube image build -t local/devex:v1 .
    - name: Deploy to minikube
      run: kubectl apply -f k8s/

    - name: Sleep 10 seconds
      run: sleep 10

    - name: Check pods
      run: kubectl get pods -A

    